title: Stack Problems
description: My Personal Stack Problems
author: LP Devs
github: https://github.com/lpdevs
about: I am a software programmer. I am advanced in C/C++; intermediate in java (android), javascript, html, css and beginner in nodejs. 
disqus_shortname: phamvanlam
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/lpdevs"
    - icon: fa-stack-overflow
      link: "http://stackoverflow.com/users/5829049/lampv"
    - icon: fa-wordpress
      link: "http://phamvanlam.com/"  
    - icon: fa-facebook
      link: "https://www.facebook.com/wpphamvanlamcom"
    - icon: fa-twitter
      link: "https://twitter.com/phamvanlam_com"

share:
  twitter_username: phamvanlam_com
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://lpdevs.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
